### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by tangkai007** [baijiacms/baijiacmsV3#13]
突然在访问的时候出现这个错误，是什么原因？Fatal error: Call to undefined method publicAddons::setOrderCredit() in /opt/lampp/htdocs/system/public/class/web/index.php on line 22

**Comment by baijiacms** [comment]
确认问题，已修复，感谢支持！

**Comment by tangkai007** [comment]
订单邮件通知也有问题，不能讲商品信息发送到替换到邮件里

**Comment by baijiacms** [comment]
邮件信息在V3.2.1版本已经修复过了，请确认下，谢谢。

**Comment by tangkai007** [comment]
能不能做的像饿了么一样
