### ISSUE TITLE
打开商城无法自动获取用户信息登陆，需要手动注册账号！

### ISSUE THREAD

**Issue by wuzezhong** [baijiacms/baijiacmsV3#14]
点我商城——我的——然后页面有我的订单一栏，然后下面是用户登陆和用户注册。不是自动获取数据登陆的。因为我关注你们baijiacms的公帐号有看到可以自动获取用户数据登陆。

**Comment by baijiacms** [comment]
需要正确配置才能使用微信快捷登陆功能。您可以参考文档使用，这里不提供此方面支持。文档地址：https://github.com/baijiacms/baijiacmsV2/wiki
