### ISSUE TITLE
连接被重置

### ISSUE THREAD

**Issue by dengjihai** [baijiacms/baijiacmsV3#15]
在微信号位置，以及配送方式设置的时候，点击保存，总是出现“连接被重置”的问题，10次有9次出现，请问这是什么问题？现在微信快捷登录的功能都无法进行使用

**Comment by baijiacms** [comment]
1.可能是php环境问题，环境不支持iis。支持apache或者nginx+php5.3以上版本
2.快捷登录配置参考帮助文档https://github.com/baijiacms/baijiacmsV2/wiki。正确配置，且微信号需认证才能使用快捷登陆方式。

**Comment by baijiacms** [comment]
演示版本与现开源版本一致，没有发现此类问题。
