### ISSUE TITLE
微信支付提示缺少参数total_fee

### ISSUE THREAD

**Issue by kfliujian** [baijiacms/baijiacmsV3#16]
按照说明配置后出现的问题：
描述：抓到xml包里面参数是齐全的，但是就是不能吊起支付。
其他情况：二维码支付正常。

**Comment by baijiacms** [comment]
演示版与开源版版本一致，支付没有发现此类问题。

**Comment by yifucheng** [comment]
V3的描述图片不能像V2那样直接复制淘宝描述图片。因为V2复制过来的图片是等比缩放的，不会变形，然V3的不能实现等比缩放，复制过来保存之后全部变形了，如何解决？是否可以增加货到付款功能？默认模板是否可以多几个？

**Comment by kfliujian** [comment]
我后来解决了该问题，是因为微信授权用户获取权限的域名与CMS中不一致造成的。因为没有仔细研究baijiacms中用户授权获取code的具体文件，所以我直接授权了cms的所在域名，并修改了我现有页面来接受cms的一个页面转过来的code。
