### ISSUE TITLE
图片无法等比缩放

### ISSUE THREAD

**Issue by yifucheng** [baijiacms/baijiacmsV3#17]
V3的描述图片不能像V2那样直接复制淘宝描述图片。因为V2复制过来的图片是等比缩放的，不会变形，然V3的不能实现等比缩放，复制过来保存之后全部变形了，如何解决？是否可以增加货到付款功能？默认模板是否可以多几个？

**Comment by baijiacms** [comment]
不提供货到付款的功能。 V3界面有调整,使用过程中没有遇到等比缩放的问题。可上传图片后自行调整下样式。
