### ISSUE TITLE
V3无法安装，

### ISSUE THREAD

**Issue by hackgyj** [baijiacms/baijiacmsV3#7]
> 程序依赖环境检查
PHP版本(最低PHP 5.3)：  检查通过
config文件夹读写：  检查通过
themes文件夹读写：  检查通过
cache文件夹读写：  检查通过
attachment文件夹读写：  检查通过
pdo_mysql：  检查通过
pdo_mysql：  检查通过
allow_url_fopen：  检查通过
file_get_contents：  检查通过
xml_parser_create：  检查通过
curl_init：  检查通过

> 请解决环境问题后，刷新此页面，进行下一步操作。

所有都通过，但没有下一步按钮，何故？？？

**Comment by baijiacms** [comment]
热心用户”﹎`点点“的发现。PHP5.7环境不支持 mysql_connect 照成的，请使用 php5.6版本，或修改支持mysql_connect 。安装程序已更新。

**Comment by hackgyj** [comment]
收到！
