### ISSUE TITLE
银联在线支付接口问题

### ISSUE THREAD

**Issue by Hallett88** [baijiacms/baijiacmsV3#9]
按照贵公司微商城的后台提供的银联在线支付接口的条件进行配置，但却老是配置不了？是什么情况呢？

**Comment by baijiacms** [comment]
第一步需要先切换“切换到测试地址”进行测试，需要在pc端测试，测试地址在手机端一律都是证书问题。
测试通过后，在银联获得正式接入后，切换“切换到运营地址“。
